/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.sargunv.pokekotlin.models

import dev.sargunv.pokekotlin.models.AbilityChangeEffectText
import dev.sargunv.pokekotlin.models.VersionGroupSummary

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param versionGroup 
 * @param effectEntries 
 */
@Serializable

public data class AbilityChange (

    @SerialName(value = "version_group") @Required val versionGroup: VersionGroupSummary,

    @SerialName(value = "effect_entries") @Required val effectEntries: kotlin.collections.List<AbilityChangeEffectText>

) {


}

