/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.sargunv.pokekotlin.models

import dev.sargunv.pokekotlin.models.AbilityChange
import dev.sargunv.pokekotlin.models.AbilityDetailPokemonInner
import dev.sargunv.pokekotlin.models.AbilityEffectText
import dev.sargunv.pokekotlin.models.AbilityFlavorText
import dev.sargunv.pokekotlin.models.AbilityName
import dev.sargunv.pokekotlin.models.GenerationSummary

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param name 
 * @param generation 
 * @param names 
 * @param effectEntries 
 * @param effectChanges 
 * @param flavorTextEntries 
 * @param pokemon 
 * @param isMainSeries 
 */
@Serializable

public data class AbilityDetail (

    @SerialName(value = "id") @Required val id: kotlin.Int,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "generation") @Required val generation: GenerationSummary,

    @SerialName(value = "names") @Required val names: kotlin.collections.List<AbilityName>,

    @SerialName(value = "effect_entries") @Required val effectEntries: kotlin.collections.List<AbilityEffectText>,

    @SerialName(value = "effect_changes") @Required val effectChanges: kotlin.collections.List<AbilityChange>,

    @SerialName(value = "flavor_text_entries") @Required val flavorTextEntries: kotlin.collections.List<AbilityFlavorText>,

    @SerialName(value = "pokemon") @Required val pokemon: kotlin.collections.List<AbilityDetailPokemonInner>,

    @SerialName(value = "is_main_series") val isMainSeries: kotlin.Boolean? = null

) {


}

