/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.sargunv.pokekotlin.models

import dev.sargunv.pokekotlin.models.BerryDetailFlavorsInner
import dev.sargunv.pokekotlin.models.BerryFirmnessSummary
import dev.sargunv.pokekotlin.models.ItemSummary
import dev.sargunv.pokekotlin.models.TypeSummary

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param name 
 * @param growthTime 
 * @param maxHarvest 
 * @param naturalGiftPower 
 * @param propertySize 
 * @param smoothness 
 * @param soilDryness 
 * @param firmness 
 * @param flavors 
 * @param item 
 * @param naturalGiftType 
 */
@Serializable

public data class BerryDetail (

    @SerialName(value = "id") @Required val id: kotlin.Int,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "growth_time") @Required val growthTime: kotlin.Int,

    @SerialName(value = "max_harvest") @Required val maxHarvest: kotlin.Int,

    @SerialName(value = "natural_gift_power") @Required val naturalGiftPower: kotlin.Int,

    @SerialName(value = "size") @Required val propertySize: kotlin.Int,

    @SerialName(value = "smoothness") @Required val smoothness: kotlin.Int,

    @SerialName(value = "soil_dryness") @Required val soilDryness: kotlin.Int,

    @SerialName(value = "firmness") @Required val firmness: BerryFirmnessSummary,

    @SerialName(value = "flavors") @Required val flavors: kotlin.collections.List<BerryDetailFlavorsInner>,

    @SerialName(value = "item") @Required val item: ItemSummary,

    @SerialName(value = "natural_gift_type") @Required val naturalGiftType: TypeSummary

) {


}

