/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.sargunv.pokekotlin.models

import dev.sargunv.pokekotlin.models.BerryDetailFlavorsInnerFlavor

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param potency 
 * @param flavor 
 */
@Serializable

public data class BerryDetailFlavorsInner (

    @SerialName(value = "potency") @Required val potency: kotlin.Int,

    @SerialName(value = "flavor") @Required val flavor: BerryDetailFlavorsInnerFlavor

) {


}

