/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.sargunv.pokekotlin.models

import dev.sargunv.pokekotlin.models.BerryFirmnessName
import dev.sargunv.pokekotlin.models.BerrySummary

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param name 
 * @param berries 
 * @param names 
 */
@Serializable

public data class BerryFirmnessDetail (

    @SerialName(value = "id") @Required val id: kotlin.Int,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "berries") @Required val berries: kotlin.collections.List<BerrySummary>,

    @SerialName(value = "names") @Required val names: kotlin.collections.List<BerryFirmnessName>

) {


}

