/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.sargunv.pokekotlin.models

import dev.sargunv.pokekotlin.models.CharacteristicDescription
import dev.sargunv.pokekotlin.models.StatSummary

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param geneModulo 
 * @param possibleValues 
 * @param highestStat 
 * @param descriptions 
 */
@Serializable

public data class CharacteristicDetail (

    @SerialName(value = "id") @Required val id: kotlin.Int,

    @SerialName(value = "gene_modulo") @Required val geneModulo: kotlin.Int,

    @SerialName(value = "possible_values") @Required val possibleValues: kotlin.collections.List<kotlin.Int>,

    @SerialName(value = "highest_stat") @Required val highestStat: StatSummary,

    @SerialName(value = "descriptions") @Required val descriptions: kotlin.collections.List<CharacteristicDescription>

) {


}

