/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.sargunv.pokekotlin.models

import dev.sargunv.pokekotlin.models.BerryFlavorSummary
import dev.sargunv.pokekotlin.models.ContestTypeName

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param name 
 * @param berryFlavor 
 * @param names 
 */
@Serializable

public data class ContestTypeDetail (

    @SerialName(value = "id") @Required val id: kotlin.Int,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "berry_flavor") @Required val berryFlavor: BerryFlavorSummary,

    @SerialName(value = "names") @Required val names: kotlin.collections.List<ContestTypeName>

) {


}

