/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.sargunv.pokekotlin.models

import dev.sargunv.pokekotlin.models.ContestEffectEffectText
import dev.sargunv.pokekotlin.models.ContestEffectFlavorText

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param appeal 
 * @param jam 
 * @param effectEntries 
 * @param flavorTextEntries 
 */
@Serializable

public data class ContestEffectDetail (

    @SerialName(value = "id") @Required val id: kotlin.Int,

    @SerialName(value = "appeal") @Required val appeal: kotlin.Int,

    @SerialName(value = "jam") @Required val jam: kotlin.Int,

    @SerialName(value = "effect_entries") @Required val effectEntries: kotlin.collections.List<ContestEffectEffectText>,

    @SerialName(value = "flavor_text_entries") @Required val flavorTextEntries: kotlin.collections.List<ContestEffectFlavorText>

) {


}

