/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.sargunv.pokekotlin.models

import dev.sargunv.pokekotlin.models.EncounterConditionSummary
import dev.sargunv.pokekotlin.models.EncounterConditionValueName

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param name 
 * @param condition 
 * @param names 
 */
@Serializable

public data class EncounterConditionValueDetail (

    @SerialName(value = "id") @Required val id: kotlin.Int,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "condition") @Required val condition: EncounterConditionSummary,

    @SerialName(value = "names") @Required val names: kotlin.collections.List<EncounterConditionValueName>

) {


}

