/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.sargunv.pokekotlin.models

import dev.sargunv.pokekotlin.models.EvolutionChainDetailChain
import dev.sargunv.pokekotlin.models.ItemSummary

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param babyTriggerItem 
 * @param chain 
 */
@Serializable

public data class EvolutionChainDetail (

    @SerialName(value = "id") @Required val id: kotlin.Int,

    @SerialName(value = "baby_trigger_item") @Required val babyTriggerItem: ItemSummary,

    @SerialName(value = "chain") @Required val chain: EvolutionChainDetailChain

) {


}

