/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.sargunv.pokekotlin.models

import dev.sargunv.pokekotlin.models.AbilityDetailPokemonInnerPokemon
import dev.sargunv.pokekotlin.models.EvolutionChainLinkDetailsGender

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param gender 
 * @param heldItem 
 * @param item 
 * @param knownMove 
 * @param knownMoveType 
 * @param location 
 * @param minAffection 
 * @param minBeauty 
 * @param minHappiness 
 * @param minLevel 
 * @param needsOverworldRain 
 * @param partySpecies 
 * @param partyType 
 * @param relativePhysicalStats 
 * @param timeOfDay 
 * @param tradeSpecies 
 * @param trigger 
 * @param turnUpsideDown 
 */
@Serializable

public data class EvolutionChainLinkDetails (

    @SerialName(value = "gender") @Required val gender: EvolutionChainLinkDetailsGender,

    @SerialName(value = "held_item") @Required val heldItem: EvolutionChainLinkDetailsGender,

    @SerialName(value = "item") @Required val item: EvolutionChainLinkDetailsGender,

    @SerialName(value = "known_move") @Required val knownMove: kotlin.String,

    @SerialName(value = "known_move_type") @Required val knownMoveType: kotlin.String,

    @SerialName(value = "location") @Required val location: EvolutionChainLinkDetailsGender,

    @SerialName(value = "min_affection") @Required val minAffection: kotlin.Int,

    @SerialName(value = "min_beauty") @Required val minBeauty: kotlin.Int,

    @SerialName(value = "min_happiness") @Required val minHappiness: kotlin.Int,

    @SerialName(value = "min_level") @Required val minLevel: kotlin.Int,

    @SerialName(value = "needs_overworld_rain") @Required val needsOverworldRain: kotlin.Boolean,

    @SerialName(value = "party_species") @Required val partySpecies: kotlin.String,

    @SerialName(value = "party_type") @Required val partyType: kotlin.String,

    @SerialName(value = "relative_physical_stats") @Required val relativePhysicalStats: kotlin.String,

    @SerialName(value = "time_of_day") @Required val timeOfDay: kotlin.String,

    @SerialName(value = "trade_species") @Required val tradeSpecies: kotlin.String,

    @SerialName(value = "trigger") @Required val trigger: AbilityDetailPokemonInnerPokemon,

    @SerialName(value = "turn_upside_down") @Required val turnUpsideDown: kotlin.Boolean

) {


}

