/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.sargunv.pokekotlin.models

import dev.sargunv.pokekotlin.models.AbilityDetailPokemonInnerPokemon
import dev.sargunv.pokekotlin.models.EvolutionChainLinkDetails

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param evolutionDetails 
 * @param isBaby 
 * @param species 
 */
@Serializable

public data class EvolutionChainDetailChainEvolvesToInner (

    @SerialName(value = "evolution_details") @Required val evolutionDetails: kotlin.collections.List<EvolutionChainLinkDetails>,

    @SerialName(value = "is_baby") @Required val isBaby: kotlin.Boolean,

    @SerialName(value = "species") @Required val species: AbilityDetailPokemonInnerPokemon

) {


}

