/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.sargunv.pokekotlin.models

import dev.sargunv.pokekotlin.models.AbilitySummary
import dev.sargunv.pokekotlin.models.GenerationName
import dev.sargunv.pokekotlin.models.MoveSummary
import dev.sargunv.pokekotlin.models.PokemonSpeciesSummary
import dev.sargunv.pokekotlin.models.RegionSummary
import dev.sargunv.pokekotlin.models.TypeSummary
import dev.sargunv.pokekotlin.models.VersionGroupSummary

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param name 
 * @param abilities 
 * @param mainRegion 
 * @param moves 
 * @param names 
 * @param pokemonSpecies 
 * @param types 
 * @param versionGroups 
 */
@Serializable

public data class GenerationDetail (

    @SerialName(value = "id") @Required val id: kotlin.Int,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "abilities") @Required val abilities: kotlin.collections.List<AbilitySummary>,

    @SerialName(value = "main_region") @Required val mainRegion: RegionSummary,

    @SerialName(value = "moves") @Required val moves: kotlin.collections.List<MoveSummary>,

    @SerialName(value = "names") @Required val names: kotlin.collections.List<GenerationName>,

    @SerialName(value = "pokemon_species") @Required val pokemonSpecies: kotlin.collections.List<PokemonSpeciesSummary>,

    @SerialName(value = "types") @Required val types: kotlin.collections.List<TypeSummary>,

    @SerialName(value = "version_groups") @Required val versionGroups: kotlin.collections.List<VersionGroupSummary>

) {


}

