/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.sargunv.pokekotlin.models

import dev.sargunv.pokekotlin.models.Experience
import dev.sargunv.pokekotlin.models.GrowthRateDescription
import dev.sargunv.pokekotlin.models.PokemonSpeciesSummary

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param name 
 * @param formula 
 * @param descriptions 
 * @param levels 
 * @param pokemonSpecies 
 */
@Serializable

public data class GrowthRateDetail (

    @SerialName(value = "id") @Required val id: kotlin.Int,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "formula") @Required val formula: kotlin.String,

    @SerialName(value = "descriptions") @Required val descriptions: kotlin.collections.List<GrowthRateDescription>,

    @SerialName(value = "levels") @Required val levels: kotlin.collections.List<Experience>,

    @SerialName(value = "pokemon_species") @Required val pokemonSpecies: kotlin.collections.List<PokemonSpeciesSummary>

) {


}

