/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.sargunv.pokekotlin.models

import dev.sargunv.pokekotlin.models.AbilityDetailPokemonInnerPokemon

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param rarity 
 * @param version 
 */
@Serializable

public data class ItemDetailHeldByPokemonInnerVersionDetailsInner (

    @SerialName(value = "rarity") @Required val rarity: kotlin.Int,

    @SerialName(value = "version") @Required val version: AbilityDetailPokemonInnerPokemon

) {


}

