/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.sargunv.pokekotlin.models

import dev.sargunv.pokekotlin.models.AbilityDetailPokemonInnerPokemon
import dev.sargunv.pokekotlin.models.ItemCategorySummary
import dev.sargunv.pokekotlin.models.ItemDetailBabyTriggerFor
import dev.sargunv.pokekotlin.models.ItemDetailHeldByPokemonInner
import dev.sargunv.pokekotlin.models.ItemDetailMachinesInner
import dev.sargunv.pokekotlin.models.ItemDetailSprites
import dev.sargunv.pokekotlin.models.ItemEffectText
import dev.sargunv.pokekotlin.models.ItemFlavorText
import dev.sargunv.pokekotlin.models.ItemFlingEffectSummary
import dev.sargunv.pokekotlin.models.ItemGameIndex
import dev.sargunv.pokekotlin.models.ItemName

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param name 
 * @param flingEffect 
 * @param attributes 
 * @param category 
 * @param effectEntries 
 * @param flavorTextEntries 
 * @param gameIndices 
 * @param names 
 * @param heldByPokemon 
 * @param sprites 
 * @param babyTriggerFor 
 * @param machines 
 * @param cost 
 * @param flingPower 
 */
@Serializable

public data class ItemDetail (

    @SerialName(value = "id") @Required val id: kotlin.Int,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "fling_effect") @Required val flingEffect: ItemFlingEffectSummary,

    @SerialName(value = "attributes") @Required val attributes: kotlin.collections.List<AbilityDetailPokemonInnerPokemon>,

    @SerialName(value = "category") @Required val category: ItemCategorySummary,

    @SerialName(value = "effect_entries") @Required val effectEntries: kotlin.collections.List<ItemEffectText>,

    @SerialName(value = "flavor_text_entries") @Required val flavorTextEntries: kotlin.collections.List<ItemFlavorText>,

    @SerialName(value = "game_indices") @Required val gameIndices: kotlin.collections.List<ItemGameIndex>,

    @SerialName(value = "names") @Required val names: kotlin.collections.List<ItemName>,

    @SerialName(value = "held_by_pokemon") @Required val heldByPokemon: kotlin.collections.List<ItemDetailHeldByPokemonInner>,

    @SerialName(value = "sprites") @Required val sprites: ItemDetailSprites,

    @SerialName(value = "baby_trigger_for") @Required val babyTriggerFor: ItemDetailBabyTriggerFor,

    @SerialName(value = "machines") @Required val machines: kotlin.collections.List<ItemDetailMachinesInner>,

    @SerialName(value = "cost") val cost: kotlin.Int? = null,

    @SerialName(value = "fling_power") val flingPower: kotlin.Int? = null

) {


}

