/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.sargunv.pokekotlin.models

import dev.sargunv.pokekotlin.models.AbilityDetailPokemonInnerPokemon

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param machine 
 * @param versionGroup 
 */
@Serializable

public data class ItemDetailMachinesInner (

    @SerialName(value = "machine") @Required val machine: kotlin.String,

    @SerialName(value = "version_group") @Required val versionGroup: AbilityDetailPokemonInnerPokemon

) {


}

