/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.sargunv.pokekotlin.models

import dev.sargunv.pokekotlin.models.LanguageSummary
import dev.sargunv.pokekotlin.models.VersionGroupSummary

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param text 
 * @param versionGroup 
 * @param language 
 */
@Serializable

public data class ItemFlavorText (

    @SerialName(value = "text") @Required val text: kotlin.String,

    @SerialName(value = "version_group") @Required val versionGroup: VersionGroupSummary,

    @SerialName(value = "language") @Required val language: LanguageSummary

) {


}

