/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.sargunv.pokekotlin.models

import dev.sargunv.pokekotlin.models.AbilityDetailPokemonInnerPokemon
import dev.sargunv.pokekotlin.models.ItemAttributeDescription
import dev.sargunv.pokekotlin.models.ItemAttributeName

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param name 
 * @param descriptions 
 * @param items 
 * @param names 
 */
@Serializable

public data class ItemAttributeDetail (

    @SerialName(value = "id") @Required val id: kotlin.Int,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "descriptions") @Required val descriptions: kotlin.collections.List<ItemAttributeDescription>,

    @SerialName(value = "items") @Required val items: kotlin.collections.List<AbilityDetailPokemonInnerPokemon>,

    @SerialName(value = "names") @Required val names: kotlin.collections.List<ItemAttributeName>

) {


}

