/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.sargunv.pokekotlin.models

import dev.sargunv.pokekotlin.models.ItemFlingEffectEffectText
import dev.sargunv.pokekotlin.models.ItemSummary

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param name 
 * @param effectEntries 
 * @param items 
 */
@Serializable

public data class ItemFlingEffectDetail (

    @SerialName(value = "id") @Required val id: kotlin.Int,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "effect_entries") @Required val effectEntries: kotlin.collections.List<ItemFlingEffectEffectText>,

    @SerialName(value = "items") @Required val items: kotlin.collections.List<ItemSummary>

) {


}

