/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.sargunv.pokekotlin.models

import dev.sargunv.pokekotlin.models.ItemCategoryName
import dev.sargunv.pokekotlin.models.ItemPocketSummary
import dev.sargunv.pokekotlin.models.ItemSummary

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param name 
 * @param items 
 * @param names 
 * @param pocket 
 */
@Serializable

public data class ItemCategoryDetail (

    @SerialName(value = "id") @Required val id: kotlin.Int,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "items") @Required val items: kotlin.collections.List<ItemSummary>,

    @SerialName(value = "names") @Required val names: kotlin.collections.List<ItemCategoryName>,

    @SerialName(value = "pocket") @Required val pocket: ItemPocketSummary

) {


}

