/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.sargunv.pokekotlin.models

import dev.sargunv.pokekotlin.models.ItemCategorySummary
import dev.sargunv.pokekotlin.models.ItemPocketName

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param name 
 * @param categories 
 * @param names 
 */
@Serializable

public data class ItemPocketDetail (

    @SerialName(value = "id") @Required val id: kotlin.Int,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "categories") @Required val categories: kotlin.collections.List<ItemCategorySummary>,

    @SerialName(value = "names") @Required val names: kotlin.collections.List<ItemPocketName>

) {


}

