/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.sargunv.pokekotlin.models

import dev.sargunv.pokekotlin.models.LanguageName

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param name 
 * @param iso639 
 * @param iso3166 
 * @param names 
 * @param official 
 */
@Serializable

public data class LanguageDetail (

    @SerialName(value = "id") @Required val id: kotlin.Int,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "iso639") @Required val iso639: kotlin.String,

    @SerialName(value = "iso3166") @Required val iso3166: kotlin.String,

    @SerialName(value = "names") @Required val names: kotlin.collections.List<LanguageName>,

    @SerialName(value = "official") val official: kotlin.Boolean? = null

) {


}

