/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.sargunv.pokekotlin.models

import dev.sargunv.pokekotlin.models.AbilityDetailPokemonInnerPokemon

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param minLevel 
 * @param maxLevel 
 * @param chance 
 * @param method 
 * @param conditionValues 
 */
@Serializable

public data class LocationAreaDetailPokemonEncountersInnerVersionDetailsInnerEncounterDetails (

    @SerialName(value = "min_level") @Required val minLevel: kotlin.Int,

    @SerialName(value = "max_level") @Required val maxLevel: kotlin.Int,

    @SerialName(value = "chance") @Required val chance: kotlin.Int,

    @SerialName(value = "method") @Required val method: AbilityDetailPokemonInnerPokemon,

    @SerialName(value = "condition_values") val conditionValues: AbilityDetailPokemonInnerPokemon? = null

) {


}

