/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.sargunv.pokekotlin.models

import dev.sargunv.pokekotlin.models.LocationAreaDetailEncounterMethodRatesInner
import dev.sargunv.pokekotlin.models.LocationAreaDetailPokemonEncountersInner
import dev.sargunv.pokekotlin.models.LocationAreaName
import dev.sargunv.pokekotlin.models.LocationSummary

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param name 
 * @param gameIndex 
 * @param encounterMethodRates 
 * @param location 
 * @param names 
 * @param pokemonEncounters 
 */
@Serializable

public data class LocationAreaDetail (

    @SerialName(value = "id") @Required val id: kotlin.Int,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "game_index") @Required val gameIndex: kotlin.Int,

    @SerialName(value = "encounter_method_rates") @Required val encounterMethodRates: kotlin.collections.List<LocationAreaDetailEncounterMethodRatesInner>,

    @SerialName(value = "location") @Required val location: LocationSummary,

    @SerialName(value = "names") @Required val names: kotlin.collections.List<LocationAreaName>,

    @SerialName(value = "pokemon_encounters") @Required val pokemonEncounters: kotlin.collections.List<LocationAreaDetailPokemonEncountersInner>

) {


}

