/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.sargunv.pokekotlin.models

import dev.sargunv.pokekotlin.models.AbilityDetailPokemonInnerPokemon
import dev.sargunv.pokekotlin.models.LocationAreaDetailPokemonEncountersInnerVersionDetailsInner

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param pokemon 
 * @param versionDetails 
 */
@Serializable

public data class LocationAreaDetailPokemonEncountersInner (

    @SerialName(value = "pokemon") @Required val pokemon: AbilityDetailPokemonInnerPokemon,

    @SerialName(value = "version_details") @Required val versionDetails: kotlin.collections.List<LocationAreaDetailPokemonEncountersInnerVersionDetailsInner>

) {


}

