/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.sargunv.pokekotlin.models

import dev.sargunv.pokekotlin.models.AbilityDetailPokemonInnerPokemon
import dev.sargunv.pokekotlin.models.LocationAreaDetailPokemonEncountersInnerVersionDetailsInnerEncounterDetails

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param version 
 * @param maxChance 
 * @param encounterDetails 
 */
@Serializable

public data class LocationAreaDetailPokemonEncountersInnerVersionDetailsInner (

    @SerialName(value = "version") @Required val version: AbilityDetailPokemonInnerPokemon,

    @SerialName(value = "max_chance") @Required val maxChance: kotlin.Int,

    @SerialName(value = "encounter_details") @Required val encounterDetails: LocationAreaDetailPokemonEncountersInnerVersionDetailsInnerEncounterDetails

) {


}

