/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.sargunv.pokekotlin.models

import dev.sargunv.pokekotlin.models.LocationAreaSummary
import dev.sargunv.pokekotlin.models.LocationGameIndex
import dev.sargunv.pokekotlin.models.LocationName
import dev.sargunv.pokekotlin.models.RegionSummary

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param name 
 * @param region 
 * @param names 
 * @param gameIndices 
 * @param areas 
 */
@Serializable

public data class LocationDetail (

    @SerialName(value = "id") @Required val id: kotlin.Int,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "region") @Required val region: RegionSummary,

    @SerialName(value = "names") @Required val names: kotlin.collections.List<LocationName>,

    @SerialName(value = "game_indices") @Required val gameIndices: kotlin.collections.List<LocationGameIndex>,

    @SerialName(value = "areas") @Required val areas: kotlin.collections.List<LocationAreaSummary>

) {


}

