/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.sargunv.pokekotlin.models

import dev.sargunv.pokekotlin.models.ItemSummary
import dev.sargunv.pokekotlin.models.MoveSummary
import dev.sargunv.pokekotlin.models.VersionGroupSummary

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param item 
 * @param versionGroup 
 * @param move 
 */
@Serializable

public data class MachineDetail (

    @SerialName(value = "id") @Required val id: kotlin.Int,

    @SerialName(value = "item") @Required val item: ItemSummary,

    @SerialName(value = "version_group") @Required val versionGroup: VersionGroupSummary,

    @SerialName(value = "move") @Required val move: MoveSummary

) {


}

