/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.sargunv.pokekotlin.models

import dev.sargunv.pokekotlin.models.MoveMetaAilmentSummary
import dev.sargunv.pokekotlin.models.MoveMetaCategorySummary

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param ailment 
 * @param category 
 * @param minHits 
 * @param maxHits 
 * @param minTurns 
 * @param maxTurns 
 * @param drain 
 * @param healing 
 * @param critRate 
 * @param ailmentChance 
 * @param flinchChance 
 * @param statChance 
 */
@Serializable

public data class MoveMeta (

    @SerialName(value = "ailment") @Required val ailment: MoveMetaAilmentSummary,

    @SerialName(value = "category") @Required val category: MoveMetaCategorySummary,

    @SerialName(value = "min_hits") val minHits: kotlin.Int? = null,

    @SerialName(value = "max_hits") val maxHits: kotlin.Int? = null,

    @SerialName(value = "min_turns") val minTurns: kotlin.Int? = null,

    @SerialName(value = "max_turns") val maxTurns: kotlin.Int? = null,

    @SerialName(value = "drain") val drain: kotlin.Int? = null,

    @SerialName(value = "healing") val healing: kotlin.Int? = null,

    @SerialName(value = "crit_rate") val critRate: kotlin.Int? = null,

    @SerialName(value = "ailment_chance") val ailmentChance: kotlin.Int? = null,

    @SerialName(value = "flinch_chance") val flinchChance: kotlin.Int? = null,

    @SerialName(value = "stat_chance") val statChance: kotlin.Int? = null

) {


}

