/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.sargunv.pokekotlin.models

import dev.sargunv.pokekotlin.models.MoveDamageClassDescription
import dev.sargunv.pokekotlin.models.MoveDamageClassName
import dev.sargunv.pokekotlin.models.MoveSummary

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param name 
 * @param descriptions 
 * @param moves 
 * @param names 
 */
@Serializable

public data class MoveDamageClassDetail (

    @SerialName(value = "id") @Required val id: kotlin.Int,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "descriptions") @Required val descriptions: kotlin.collections.List<MoveDamageClassDescription>,

    @SerialName(value = "moves") @Required val moves: kotlin.collections.List<MoveSummary>,

    @SerialName(value = "names") @Required val names: kotlin.collections.List<MoveDamageClassName>

) {


}

