/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.sargunv.pokekotlin.models

import dev.sargunv.pokekotlin.models.AbilityDetailPokemonInnerPokemon
import dev.sargunv.pokekotlin.models.MoveDetailEffectChangesInnerEffectEntriesInner

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param effectEntries 
 * @param versionGroup 
 */
@Serializable

public data class MoveDetailEffectChangesInner (

    @SerialName(value = "effect_entries") @Required val effectEntries: kotlin.collections.List<MoveDetailEffectChangesInnerEffectEntriesInner>,

    @SerialName(value = "version_group") @Required val versionGroup: AbilityDetailPokemonInnerPokemon

) {


}

