/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.sargunv.pokekotlin.models

import dev.sargunv.pokekotlin.models.MoveChangeEffectEntriesInner
import dev.sargunv.pokekotlin.models.TypeSummary
import dev.sargunv.pokekotlin.models.VersionGroupSummary

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param effectChance 
 * @param effectEntries 
 * @param type 
 * @param versionGroup 
 * @param accuracy 
 * @param power 
 * @param pp 
 */
@Serializable

public data class MoveChange (

    @SerialName(value = "effect_chance") @Required val effectChance: kotlin.Int,

    @SerialName(value = "effect_entries") @Required val effectEntries: kotlin.collections.List<MoveChangeEffectEntriesInner>,

    @SerialName(value = "type") @Required val type: TypeSummary,

    @SerialName(value = "version_group") @Required val versionGroup: VersionGroupSummary,

    @SerialName(value = "accuracy") val accuracy: kotlin.Int? = null,

    @SerialName(value = "power") val power: kotlin.Int? = null,

    @SerialName(value = "pp") val pp: kotlin.Int? = null

) {


}

