/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.sargunv.pokekotlin.models

import dev.sargunv.pokekotlin.models.AbilityDetailPokemonInnerPokemon

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param useBefore 
 * @param useAfter 
 */
@Serializable

public data class MoveDetailContestCombosNormal (

    @SerialName(value = "use_before") @Required val useBefore: kotlin.collections.List<AbilityDetailPokemonInnerPokemon>,

    @SerialName(value = "use_after") @Required val useAfter: kotlin.collections.List<AbilityDetailPokemonInnerPokemon>

) {


}

