/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.sargunv.pokekotlin.models

import dev.sargunv.pokekotlin.models.AbilityDetailPokemonInnerPokemon

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param change 
 * @param stat 
 */
@Serializable

public data class MoveDetailStatChangesInner (

    @SerialName(value = "change") @Required val change: kotlin.Int,

    @SerialName(value = "stat") @Required val stat: AbilityDetailPokemonInnerPokemon

) {


}

