/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.sargunv.pokekotlin.models

import dev.sargunv.pokekotlin.models.MoveDetailContestCombosNormal

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param normal 
 * @param `super` 
 */
@Serializable

public data class MoveDetailContestCombos (

    @SerialName(value = "normal") @Required val normal: MoveDetailContestCombosNormal,

    @SerialName(value = "super") @Required val `super`: MoveDetailContestCombosNormal

) {


}

