/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.sargunv.pokekotlin.models

import dev.sargunv.pokekotlin.models.AbilityDetailPokemonInnerPokemon
import dev.sargunv.pokekotlin.models.MoveLearnMethodDescription
import dev.sargunv.pokekotlin.models.MoveLearnMethodName

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param name 
 * @param names 
 * @param descriptions 
 * @param versionGroups 
 */
@Serializable

public data class MoveLearnMethodDetail (

    @SerialName(value = "id") @Required val id: kotlin.Int,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "names") @Required val names: kotlin.collections.List<MoveLearnMethodName>,

    @SerialName(value = "descriptions") @Required val descriptions: kotlin.collections.List<MoveLearnMethodDescription>,

    @SerialName(value = "version_groups") @Required val versionGroups: kotlin.collections.List<AbilityDetailPokemonInnerPokemon>

) {


}

