/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.sargunv.pokekotlin.models

import dev.sargunv.pokekotlin.models.MoveBattleStyleSummary

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param lowHpPreference 
 * @param highHpPreference 
 * @param moveBattleStyle 
 */
@Serializable

public data class NatureBattleStylePreference (

    @SerialName(value = "low_hp_preference") @Required val lowHpPreference: kotlin.Int,

    @SerialName(value = "high_hp_preference") @Required val highHpPreference: kotlin.Int,

    @SerialName(value = "move_battle_style") @Required val moveBattleStyle: MoveBattleStyleSummary

) {


}

