/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.sargunv.pokekotlin.models

import dev.sargunv.pokekotlin.models.BerryFlavorSummary
import dev.sargunv.pokekotlin.models.BerrySummary
import dev.sargunv.pokekotlin.models.NatureBattleStylePreference
import dev.sargunv.pokekotlin.models.NatureDetailPokeathlonStatChangesInner
import dev.sargunv.pokekotlin.models.NatureName
import dev.sargunv.pokekotlin.models.StatSummary

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param name 
 * @param decreasedStat 
 * @param increasedStat 
 * @param likesFlavor 
 * @param hatesFlavor 
 * @param berries 
 * @param pokeathlonStatChanges 
 * @param moveBattleStylePreferences 
 * @param names 
 */
@Serializable

public data class NatureDetail (

    @SerialName(value = "id") @Required val id: kotlin.Int,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "decreased_stat") @Required val decreasedStat: StatSummary,

    @SerialName(value = "increased_stat") @Required val increasedStat: StatSummary,

    @SerialName(value = "likes_flavor") @Required val likesFlavor: BerryFlavorSummary,

    @SerialName(value = "hates_flavor") @Required val hatesFlavor: BerryFlavorSummary,

    @SerialName(value = "berries") @Required val berries: kotlin.collections.List<BerrySummary>,

    @SerialName(value = "pokeathlon_stat_changes") @Required val pokeathlonStatChanges: kotlin.collections.List<NatureDetailPokeathlonStatChangesInner>,

    @SerialName(value = "move_battle_style_preferences") @Required val moveBattleStylePreferences: kotlin.collections.List<NatureBattleStylePreference>,

    @SerialName(value = "names") @Required val names: kotlin.collections.List<NatureName>

) {


}

