/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.sargunv.pokekotlin.models

import dev.sargunv.pokekotlin.models.AbilityDetailPokemonInnerPokemon

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param maxChange 
 * @param pokeathlonStat 
 */
@Serializable

public data class NatureDetailPokeathlonStatChangesInner (

    @SerialName(value = "max_change") @Required val maxChange: kotlin.Int,

    @SerialName(value = "pokeathlon_stat") @Required val pokeathlonStat: AbilityDetailPokemonInnerPokemon

) {


}

