/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.sargunv.pokekotlin.models

import dev.sargunv.pokekotlin.models.PokemonSpeciesSummary

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param count 
 * @param next 
 * @param previous 
 * @param results 
 */
@Serializable

public data class PaginatedPokemonSpeciesSummaryList (

    @SerialName(value = "count") val count: kotlin.Int? = null,

    @SerialName(value = "next") val next: kotlin.String? = null,

    @SerialName(value = "previous") val previous: kotlin.String? = null,

    @SerialName(value = "results") val results: kotlin.collections.List<PokemonSpeciesSummary>? = null

) {


}

