/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.sargunv.pokekotlin.models

import dev.sargunv.pokekotlin.models.AbilityDetailPokemonInnerPokemon

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param baseScore 
 * @param pokemonSpecies 
 * @param rate 
 */
@Serializable

public data class PalParkAreaDetailPokemonEncountersInner (

    @SerialName(value = "base_score") @Required val baseScore: kotlin.Int,

    @SerialName(value = "pokemon-species") @Required val pokemonSpecies: AbilityDetailPokemonInnerPokemon,

    @SerialName(value = "rate") @Required val rate: kotlin.Int

) {


}

