/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.sargunv.pokekotlin.models

import dev.sargunv.pokekotlin.models.AbilityDetailPokemonInnerPokemon

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param isDefault 
 * @param pokemon 
 */
@Serializable

public data class PokemonSpeciesDetailVarietiesInner (

    @SerialName(value = "is_default") @Required val isDefault: kotlin.Boolean,

    @SerialName(value = "pokemon") @Required val pokemon: AbilityDetailPokemonInnerPokemon

) {


}

