/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.sargunv.pokekotlin.models

import dev.sargunv.pokekotlin.models.AbilityDetailPokemonInnerPokemon
import dev.sargunv.pokekotlin.models.PokedexDescription
import dev.sargunv.pokekotlin.models.PokedexDetailPokemonEntriesInner
import dev.sargunv.pokekotlin.models.PokedexName
import dev.sargunv.pokekotlin.models.RegionSummary

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param name 
 * @param descriptions 
 * @param names 
 * @param pokemonEntries 
 * @param region 
 * @param versionGroups 
 * @param isMainSeries 
 */
@Serializable

public data class PokedexDetail (

    @SerialName(value = "id") @Required val id: kotlin.Int,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "descriptions") @Required val descriptions: kotlin.collections.List<PokedexDescription>,

    @SerialName(value = "names") @Required val names: kotlin.collections.List<PokedexName>,

    @SerialName(value = "pokemon_entries") @Required val pokemonEntries: kotlin.collections.List<PokedexDetailPokemonEntriesInner>,

    @SerialName(value = "region") @Required val region: RegionSummary,

    @SerialName(value = "version_groups") @Required val versionGroups: kotlin.collections.List<AbilityDetailPokemonInnerPokemon>,

    @SerialName(value = "is_main_series") val isMainSeries: kotlin.Boolean? = null

) {


}

