/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.sargunv.pokekotlin.models

import dev.sargunv.pokekotlin.models.PokeathlonStatDetailAffectingNatures
import dev.sargunv.pokekotlin.models.PokeathlonStatName

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param name 
 * @param affectingNatures 
 * @param names 
 */
@Serializable

public data class PokeathlonStatDetail (

    @SerialName(value = "id") @Required val id: kotlin.Int,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "affecting_natures") @Required val affectingNatures: PokeathlonStatDetailAffectingNatures,

    @SerialName(value = "names") @Required val names: kotlin.collections.List<PokeathlonStatName>

) {


}

