/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.sargunv.pokekotlin.models

import dev.sargunv.pokekotlin.models.PokemonEncountersRetrieve200ResponseInnerVersionDetailsInnerEncounterDetailsInnerConditionValuesInner
import dev.sargunv.pokekotlin.models.PokemonEncountersRetrieve200ResponseInnerVersionDetailsInnerEncounterDetailsInnerMethod

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param chance 
 * @param conditionValues 
 * @param maxLevel 
 * @param method 
 * @param minLevel 
 */
@Serializable

public data class PokemonEncountersRetrieve200ResponseInnerVersionDetailsInnerEncounterDetailsInner (

    @SerialName(value = "chance") @Required val chance: kotlin.Double,

    @SerialName(value = "condition_values") @Required val conditionValues: kotlin.collections.List<PokemonEncountersRetrieve200ResponseInnerVersionDetailsInnerEncounterDetailsInnerConditionValuesInner>,

    @SerialName(value = "max_level") @Required val maxLevel: kotlin.Double,

    @SerialName(value = "method") @Required val method: PokemonEncountersRetrieve200ResponseInnerVersionDetailsInnerEncounterDetailsInnerMethod,

    @SerialName(value = "min_level") @Required val minLevel: kotlin.Double

) {


}

