/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.sargunv.pokekotlin.models

import dev.sargunv.pokekotlin.models.PokemonEncountersRetrieve200ResponseInnerLocationArea
import dev.sargunv.pokekotlin.models.PokemonEncountersRetrieve200ResponseInnerVersionDetailsInner

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param locationArea 
 * @param versionDetails 
 */
@Serializable

public data class PokemonEncountersRetrieve200ResponseInner (

    @SerialName(value = "location_area") @Required val locationArea: PokemonEncountersRetrieve200ResponseInnerLocationArea,

    @SerialName(value = "version_details") @Required val versionDetails: kotlin.collections.List<PokemonEncountersRetrieve200ResponseInnerVersionDetailsInner>

) {


}

