/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.sargunv.pokekotlin.models

import dev.sargunv.pokekotlin.models.AbilityDetailPokemonInnerPokemon
import dev.sargunv.pokekotlin.models.PokemonDetailAbilitiesInner

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param abilities 
 * @param generation 
 */
@Serializable

public data class PokemonDetailPastAbilitiesInner (

    @SerialName(value = "abilities") @Required val abilities: kotlin.collections.List<PokemonDetailAbilitiesInner>,

    @SerialName(value = "generation") @Required val generation: AbilityDetailPokemonInnerPokemon

) {


}

