/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.sargunv.pokekotlin.models

import dev.sargunv.pokekotlin.models.AbilityDetailPokemonInnerPokemon
import dev.sargunv.pokekotlin.models.EvolutionChainSummary
import dev.sargunv.pokekotlin.models.GenerationSummary
import dev.sargunv.pokekotlin.models.GrowthRateSummary
import dev.sargunv.pokekotlin.models.PokemonColorSummary
import dev.sargunv.pokekotlin.models.PokemonDexEntry
import dev.sargunv.pokekotlin.models.PokemonFormDetailFormNamesInner
import dev.sargunv.pokekotlin.models.PokemonHabitatSummary
import dev.sargunv.pokekotlin.models.PokemonShapeSummary
import dev.sargunv.pokekotlin.models.PokemonSpeciesDescription
import dev.sargunv.pokekotlin.models.PokemonSpeciesDetailGeneraInner
import dev.sargunv.pokekotlin.models.PokemonSpeciesDetailPalParkEncountersInner
import dev.sargunv.pokekotlin.models.PokemonSpeciesDetailVarietiesInner
import dev.sargunv.pokekotlin.models.PokemonSpeciesFlavorText
import dev.sargunv.pokekotlin.models.PokemonSpeciesSummary

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param name 
 * @param growthRate 
 * @param pokedexNumbers 
 * @param eggGroups 
 * @param color 
 * @param shape 
 * @param evolvesFromSpecies 
 * @param evolutionChain 
 * @param habitat 
 * @param generation 
 * @param names 
 * @param palParkEncounters 
 * @param formDescriptions 
 * @param flavorTextEntries 
 * @param genera 
 * @param varieties 
 * @param order 
 * @param genderRate 
 * @param captureRate 
 * @param baseHappiness 
 * @param isBaby 
 * @param isLegendary 
 * @param isMythical 
 * @param hatchCounter 
 * @param hasGenderDifferences 
 * @param formsSwitchable 
 */
@Serializable

public data class PokemonSpeciesDetail (

    @SerialName(value = "id") @Required val id: kotlin.Int,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "growth_rate") @Required val growthRate: GrowthRateSummary,

    @SerialName(value = "pokedex_numbers") @Required val pokedexNumbers: kotlin.collections.List<PokemonDexEntry>,

    @SerialName(value = "egg_groups") @Required val eggGroups: kotlin.collections.List<AbilityDetailPokemonInnerPokemon>,

    @SerialName(value = "color") @Required val color: PokemonColorSummary,

    @SerialName(value = "shape") @Required val shape: PokemonShapeSummary,

    @SerialName(value = "evolves_from_species") @Required val evolvesFromSpecies: PokemonSpeciesSummary,

    @SerialName(value = "evolution_chain") @Required val evolutionChain: EvolutionChainSummary,

    @SerialName(value = "habitat") @Required val habitat: PokemonHabitatSummary,

    @SerialName(value = "generation") @Required val generation: GenerationSummary,

    @SerialName(value = "names") @Required val names: kotlin.collections.List<PokemonFormDetailFormNamesInner>,

    @SerialName(value = "pal_park_encounters") @Required val palParkEncounters: kotlin.collections.List<PokemonSpeciesDetailPalParkEncountersInner>,

    @SerialName(value = "form_descriptions") @Required val formDescriptions: kotlin.collections.List<PokemonSpeciesDescription>,

    @SerialName(value = "flavor_text_entries") @Required val flavorTextEntries: kotlin.collections.List<PokemonSpeciesFlavorText>,

    @SerialName(value = "genera") @Required val genera: kotlin.collections.List<PokemonSpeciesDetailGeneraInner>,

    @SerialName(value = "varieties") @Required val varieties: kotlin.collections.List<PokemonSpeciesDetailVarietiesInner>,

    @SerialName(value = "order") val order: kotlin.Int? = null,

    @SerialName(value = "gender_rate") val genderRate: kotlin.Int? = null,

    @SerialName(value = "capture_rate") val captureRate: kotlin.Int? = null,

    @SerialName(value = "base_happiness") val baseHappiness: kotlin.Int? = null,

    @SerialName(value = "is_baby") val isBaby: kotlin.Boolean? = null,

    @SerialName(value = "is_legendary") val isLegendary: kotlin.Boolean? = null,

    @SerialName(value = "is_mythical") val isMythical: kotlin.Boolean? = null,

    @SerialName(value = "hatch_counter") val hatchCounter: kotlin.Int? = null,

    @SerialName(value = "has_gender_differences") val hasGenderDifferences: kotlin.Boolean? = null,

    @SerialName(value = "forms_switchable") val formsSwitchable: kotlin.Boolean? = null

) {


}

