/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.sargunv.pokekotlin.models

import dev.sargunv.pokekotlin.models.StatSummary

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param baseStat 
 * @param effort 
 * @param stat 
 */
@Serializable

public data class PokemonStat (

    @SerialName(value = "base_stat") @Required val baseStat: kotlin.Int,

    @SerialName(value = "effort") @Required val effort: kotlin.Int,

    @SerialName(value = "stat") @Required val stat: StatSummary

) {


}

