/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.sargunv.pokekotlin.models

import dev.sargunv.pokekotlin.models.AbilityDetailPokemonInnerPokemon
import dev.sargunv.pokekotlin.models.PokemonDetailTypesInner

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param generation 
 * @param types 
 */
@Serializable

public data class PokemonDetailPastTypesInner (

    @SerialName(value = "generation") @Required val generation: AbilityDetailPokemonInnerPokemon,

    @SerialName(value = "types") @Required val types: kotlin.collections.List<PokemonDetailTypesInner>

) {


}

