/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.sargunv.pokekotlin.models

import dev.sargunv.pokekotlin.models.AbilityDetailPokemonInnerPokemon
import dev.sargunv.pokekotlin.models.PokemonDetailMovesInnerVersionGroupDetailsInner

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param move 
 * @param versionGroupDetails 
 */
@Serializable

public data class PokemonDetailMovesInner (

    @SerialName(value = "move") @Required val move: AbilityDetailPokemonInnerPokemon,

    @SerialName(value = "version_group_details") @Required val versionGroupDetails: kotlin.collections.List<PokemonDetailMovesInnerVersionGroupDetailsInner>

) {


}

