/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.sargunv.pokekotlin.models

import dev.sargunv.pokekotlin.models.PokemonDetailTypesInner
import dev.sargunv.pokekotlin.models.PokemonFormDetailFormNamesInner
import dev.sargunv.pokekotlin.models.PokemonFormDetailSprites
import dev.sargunv.pokekotlin.models.PokemonSummary
import dev.sargunv.pokekotlin.models.VersionGroupSummary

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param name 
 * @param formName 
 * @param pokemon 
 * @param sprites 
 * @param versionGroup 
 * @param formNames 
 * @param names 
 * @param types 
 * @param order 
 * @param formOrder 
 * @param isDefault 
 * @param isBattleOnly 
 * @param isMega 
 */
@Serializable

public data class PokemonFormDetail (

    @SerialName(value = "id") @Required val id: kotlin.Int,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "form_name") @Required val formName: kotlin.String,

    @SerialName(value = "pokemon") @Required val pokemon: PokemonSummary,

    @SerialName(value = "sprites") @Required val sprites: PokemonFormDetailSprites,

    @SerialName(value = "version_group") @Required val versionGroup: VersionGroupSummary,

    @SerialName(value = "form_names") @Required val formNames: kotlin.collections.List<PokemonFormDetailFormNamesInner>,

    @SerialName(value = "names") @Required val names: kotlin.collections.List<PokemonFormDetailFormNamesInner>,

    @SerialName(value = "types") @Required val types: kotlin.collections.List<PokemonDetailTypesInner>,

    @SerialName(value = "order") val order: kotlin.Int? = null,

    @SerialName(value = "form_order") val formOrder: kotlin.Int? = null,

    @SerialName(value = "is_default") val isDefault: kotlin.Boolean? = null,

    @SerialName(value = "is_battle_only") val isBattleOnly: kotlin.Boolean? = null,

    @SerialName(value = "is_mega") val isMega: kotlin.Boolean? = null

) {


}

