/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.sargunv.pokekotlin.models

import dev.sargunv.pokekotlin.models.AbilityDetailPokemonInnerPokemon

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param ability 
 * @param isHidden 
 * @param slot 
 */
@Serializable

public data class PokemonDetailAbilitiesInner (

    @SerialName(value = "ability") @Required val ability: AbilityDetailPokemonInnerPokemon,

    @SerialName(value = "is_hidden") @Required val isHidden: kotlin.Boolean,

    @SerialName(value = "slot") @Required val slot: kotlin.Int

) {


}

