/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.sargunv.pokekotlin.models

import dev.sargunv.pokekotlin.models.PokemonEncountersRetrieve200ResponseInnerVersionDetailsInnerEncounterDetailsInner
import dev.sargunv.pokekotlin.models.PokemonEncountersRetrieve200ResponseInnerVersionDetailsInnerVersion

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param encounterDetails 
 * @param maxChance 
 * @param version 
 */
@Serializable

public data class PokemonEncountersRetrieve200ResponseInnerVersionDetailsInner (

    @SerialName(value = "encounter_details") @Required val encounterDetails: kotlin.collections.List<PokemonEncountersRetrieve200ResponseInnerVersionDetailsInnerEncounterDetailsInner>,

    @SerialName(value = "max_chance") @Required val maxChance: kotlin.Double,

    @SerialName(value = "version") @Required val version: PokemonEncountersRetrieve200ResponseInnerVersionDetailsInnerVersion

) {


}

