/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.sargunv.pokekotlin.models

import dev.sargunv.pokekotlin.models.PokemonDetailAbilitiesInner
import dev.sargunv.pokekotlin.models.PokemonDetailCries
import dev.sargunv.pokekotlin.models.PokemonDetailHeldItems
import dev.sargunv.pokekotlin.models.PokemonDetailMovesInner
import dev.sargunv.pokekotlin.models.PokemonDetailPastAbilitiesInner
import dev.sargunv.pokekotlin.models.PokemonDetailPastTypesInner
import dev.sargunv.pokekotlin.models.PokemonDetailSprites
import dev.sargunv.pokekotlin.models.PokemonDetailTypesInner
import dev.sargunv.pokekotlin.models.PokemonFormSummary
import dev.sargunv.pokekotlin.models.PokemonGameIndex
import dev.sargunv.pokekotlin.models.PokemonSpeciesSummary
import dev.sargunv.pokekotlin.models.PokemonStat

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param name 
 * @param abilities 
 * @param pastAbilities 
 * @param forms 
 * @param gameIndices 
 * @param heldItems 
 * @param locationAreaEncounters 
 * @param moves 
 * @param species 
 * @param sprites 
 * @param cries 
 * @param stats 
 * @param types 
 * @param pastTypes 
 * @param baseExperience 
 * @param height 
 * @param isDefault 
 * @param order 
 * @param weight 
 */
@Serializable

public data class PokemonDetail (

    @SerialName(value = "id") @Required val id: kotlin.Int,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "abilities") @Required val abilities: kotlin.collections.List<PokemonDetailAbilitiesInner>,

    @SerialName(value = "past_abilities") @Required val pastAbilities: kotlin.collections.List<PokemonDetailPastAbilitiesInner>,

    @SerialName(value = "forms") @Required val forms: kotlin.collections.List<PokemonFormSummary>,

    @SerialName(value = "game_indices") @Required val gameIndices: kotlin.collections.List<PokemonGameIndex>,

    @SerialName(value = "held_items") @Required val heldItems: PokemonDetailHeldItems,

    @SerialName(value = "location_area_encounters") @Required val locationAreaEncounters: kotlin.String,

    @SerialName(value = "moves") @Required val moves: kotlin.collections.List<PokemonDetailMovesInner>,

    @SerialName(value = "species") @Required val species: PokemonSpeciesSummary,

    @SerialName(value = "sprites") @Required val sprites: PokemonDetailSprites,

    @SerialName(value = "cries") @Required val cries: PokemonDetailCries,

    @SerialName(value = "stats") @Required val stats: kotlin.collections.List<PokemonStat>,

    @SerialName(value = "types") @Required val types: kotlin.collections.List<PokemonDetailTypesInner>,

    @SerialName(value = "past_types") @Required val pastTypes: kotlin.collections.List<PokemonDetailPastTypesInner>,

    @SerialName(value = "base_experience") val baseExperience: kotlin.Int? = null,

    @SerialName(value = "height") val height: kotlin.Int? = null,

    @SerialName(value = "is_default") val isDefault: kotlin.Boolean? = null,

    @SerialName(value = "order") val order: kotlin.Int? = null,

    @SerialName(value = "weight") val weight: kotlin.Int? = null

) {


}

