/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.sargunv.pokekotlin.models

import dev.sargunv.pokekotlin.models.VersionSummary

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param gameIndex 
 * @param version 
 */
@Serializable

public data class PokemonGameIndex (

    @SerialName(value = "game_index") @Required val gameIndex: kotlin.Int,

    @SerialName(value = "version") @Required val version: VersionSummary

) {


}

