/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.sargunv.pokekotlin.models

import dev.sargunv.pokekotlin.models.LanguageSummary
import dev.sargunv.pokekotlin.models.VersionSummary

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param flavorText 
 * @param language 
 * @param version 
 */
@Serializable

public data class PokemonSpeciesFlavorText (

    @SerialName(value = "flavor_text") @Required val flavorText: kotlin.String,

    @SerialName(value = "language") @Required val language: LanguageSummary,

    @SerialName(value = "version") @Required val version: VersionSummary

) {


}

