/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.sargunv.pokekotlin.models

import dev.sargunv.pokekotlin.models.PokedexSummary

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param entryNumber 
 * @param pokedex 
 */
@Serializable

public data class PokemonDexEntry (

    @SerialName(value = "entry_number") @Required val entryNumber: kotlin.Int,

    @SerialName(value = "pokedex") @Required val pokedex: PokedexSummary

) {


}

