/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.sargunv.pokekotlin.models

import dev.sargunv.pokekotlin.models.AbilityDetailPokemonInnerPokemon

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param levelLearnedAt 
 * @param moveLearnMethod 
 * @param versionGroup 
 */
@Serializable

public data class PokemonDetailMovesInnerVersionGroupDetailsInner (

    @SerialName(value = "level_learned_at") @Required val levelLearnedAt: kotlin.Int,

    @SerialName(value = "move_learn_method") @Required val moveLearnMethod: AbilityDetailPokemonInnerPokemon,

    @SerialName(value = "version_group") @Required val versionGroup: AbilityDetailPokemonInnerPokemon

) {


}

