/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.sargunv.pokekotlin.models

import dev.sargunv.pokekotlin.models.AbilityDetailPokemonInnerPokemon
import dev.sargunv.pokekotlin.models.GenerationSummary
import dev.sargunv.pokekotlin.models.LocationSummary
import dev.sargunv.pokekotlin.models.PokedexSummary
import dev.sargunv.pokekotlin.models.RegionName

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param name 
 * @param locations 
 * @param mainGeneration 
 * @param names 
 * @param pokedexes 
 * @param versionGroups 
 */
@Serializable

public data class RegionDetail (

    @SerialName(value = "id") @Required val id: kotlin.Int,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "locations") @Required val locations: kotlin.collections.List<LocationSummary>,

    @SerialName(value = "main_generation") @Required val mainGeneration: GenerationSummary,

    @SerialName(value = "names") @Required val names: kotlin.collections.List<RegionName>,

    @SerialName(value = "pokedexes") @Required val pokedexes: kotlin.collections.List<PokedexSummary>,

    @SerialName(value = "version_groups") @Required val versionGroups: kotlin.collections.List<AbilityDetailPokemonInnerPokemon>

) {


}

