/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.sargunv.pokekotlin.models

import dev.sargunv.pokekotlin.models.AbilityDetailPokemonInnerPokemon

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param increase 
 * @param decrease 
 */
@Serializable

public data class StatDetailAffectingNatures (

    @SerialName(value = "increase") @Required val increase: kotlin.collections.List<AbilityDetailPokemonInnerPokemon>,

    @SerialName(value = "decrease") @Required val decrease: kotlin.collections.List<AbilityDetailPokemonInnerPokemon>

) {


}

