/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.sargunv.pokekotlin.models

import dev.sargunv.pokekotlin.models.CharacteristicSummary
import dev.sargunv.pokekotlin.models.MoveDamageClassSummary
import dev.sargunv.pokekotlin.models.StatDetailAffectingMoves
import dev.sargunv.pokekotlin.models.StatDetailAffectingNatures
import dev.sargunv.pokekotlin.models.StatName

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param name 
 * @param gameIndex 
 * @param affectingMoves 
 * @param affectingNatures 
 * @param characteristics 
 * @param moveDamageClass 
 * @param names 
 * @param isBattleOnly 
 */
@Serializable

public data class StatDetail (

    @SerialName(value = "id") @Required val id: kotlin.Int,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "game_index") @Required val gameIndex: kotlin.Int,

    @SerialName(value = "affecting_moves") @Required val affectingMoves: StatDetailAffectingMoves,

    @SerialName(value = "affecting_natures") @Required val affectingNatures: StatDetailAffectingNatures,

    @SerialName(value = "characteristics") @Required val characteristics: kotlin.collections.List<CharacteristicSummary>,

    @SerialName(value = "move_damage_class") @Required val moveDamageClass: MoveDamageClassSummary,

    @SerialName(value = "names") @Required val names: kotlin.collections.List<StatName>,

    @SerialName(value = "is_battle_only") val isBattleOnly: kotlin.Boolean? = null

) {


}

