/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.sargunv.pokekotlin.models

import dev.sargunv.pokekotlin.models.MoveSummary
import dev.sargunv.pokekotlin.models.SuperContestEffectFlavorText

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param appeal 
 * @param flavorTextEntries 
 * @param moves 
 */
@Serializable

public data class SuperContestEffectDetail (

    @SerialName(value = "id") @Required val id: kotlin.Int,

    @SerialName(value = "appeal") @Required val appeal: kotlin.Int,

    @SerialName(value = "flavor_text_entries") @Required val flavorTextEntries: kotlin.collections.List<SuperContestEffectFlavorText>,

    @SerialName(value = "moves") @Required val moves: kotlin.collections.List<MoveSummary>

) {


}

