/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.sargunv.pokekotlin.models

import dev.sargunv.pokekotlin.models.AbilityName
import dev.sargunv.pokekotlin.models.GenerationSummary
import dev.sargunv.pokekotlin.models.MoveDamageClassSummary
import dev.sargunv.pokekotlin.models.MoveSummary
import dev.sargunv.pokekotlin.models.TypeDetailDamageRelations
import dev.sargunv.pokekotlin.models.TypeDetailPastDamageRelationsInner
import dev.sargunv.pokekotlin.models.TypeDetailPokemonInner
import dev.sargunv.pokekotlin.models.TypeDetailSpritesValueValue
import dev.sargunv.pokekotlin.models.TypeGameIndex

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Serializer for the Type resource
 *
 * @param id 
 * @param name 
 * @param damageRelations 
 * @param pastDamageRelations 
 * @param gameIndices 
 * @param generation 
 * @param moveDamageClass 
 * @param names 
 * @param pokemon 
 * @param moves 
 * @param sprites 
 */
@Serializable

public data class TypeDetail (

    @SerialName(value = "id") @Required val id: kotlin.Int,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "damage_relations") @Required val damageRelations: TypeDetailDamageRelations,

    @SerialName(value = "past_damage_relations") @Required val pastDamageRelations: kotlin.collections.List<TypeDetailPastDamageRelationsInner>,

    @SerialName(value = "game_indices") @Required val gameIndices: kotlin.collections.List<TypeGameIndex>,

    @SerialName(value = "generation") @Required val generation: GenerationSummary,

    @SerialName(value = "move_damage_class") @Required val moveDamageClass: MoveDamageClassSummary,

    @SerialName(value = "names") @Required val names: kotlin.collections.List<AbilityName>,

    @SerialName(value = "pokemon") @Required val pokemon: kotlin.collections.List<TypeDetailPokemonInner>,

    @SerialName(value = "moves") @Required val moves: kotlin.collections.List<MoveSummary>,

    @SerialName(value = "sprites") @Required val sprites: kotlin.collections.Map<kotlin.String, kotlin.collections.Map<kotlin.String, TypeDetailSpritesValueValue>>

) {


}

