/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.sargunv.pokekotlin.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param name The name of the pokemon
 * @param url The URL to get more information about the pokemon
 */
@Serializable

public data class TypeDetailPokemonInnerPokemon (

    /* The name of the pokemon */
    @SerialName(value = "name") val name: kotlin.String? = null,

    /* The URL to get more information about the pokemon */
    @SerialName(value = "url") val url: kotlin.String? = null

) {


}

