/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.sargunv.pokekotlin.models

import dev.sargunv.pokekotlin.models.AbilityDetailPokemonInnerPokemon

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param noDamageTo 
 * @param halfDamageTo 
 * @param doubleDamageTo 
 * @param noDamageFrom 
 * @param halfDamageFrom 
 * @param doubleDamageFrom 
 */
@Serializable

public data class TypeDetailDamageRelations (

    @SerialName(value = "no_damage_to") @Required val noDamageTo: kotlin.collections.List<AbilityDetailPokemonInnerPokemon>,

    @SerialName(value = "half_damage_to") @Required val halfDamageTo: kotlin.collections.List<AbilityDetailPokemonInnerPokemon>,

    @SerialName(value = "double_damage_to") @Required val doubleDamageTo: kotlin.collections.List<AbilityDetailPokemonInnerPokemon>,

    @SerialName(value = "no_damage_from") @Required val noDamageFrom: kotlin.collections.List<AbilityDetailPokemonInnerPokemon>,

    @SerialName(value = "half_damage_from") @Required val halfDamageFrom: kotlin.collections.List<AbilityDetailPokemonInnerPokemon>,

    @SerialName(value = "double_damage_from") @Required val doubleDamageFrom: kotlin.collections.List<AbilityDetailPokemonInnerPokemon>

) {


}

