/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.sargunv.pokekotlin.models

import dev.sargunv.pokekotlin.models.AbilityDetailPokemonInnerPokemon
import dev.sargunv.pokekotlin.models.TypeDetailPastDamageRelationsInnerDamageRelations

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param generation 
 * @param damageRelations 
 */
@Serializable

public data class TypeDetailPastDamageRelationsInner (

    @SerialName(value = "generation") @Required val generation: AbilityDetailPokemonInnerPokemon,

    @SerialName(value = "damage_relations") @Required val damageRelations: TypeDetailPastDamageRelationsInnerDamageRelations

) {


}

