/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.sargunv.pokekotlin.models

import dev.sargunv.pokekotlin.models.TypeDetailPokemonInnerPokemon

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param slot 
 * @param pokemon 
 */
@Serializable

public data class TypeDetailPokemonInner (

    @SerialName(value = "slot") val slot: kotlin.Int? = null,

    @SerialName(value = "pokemon") val pokemon: TypeDetailPokemonInnerPokemon? = null

) {


}

