/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.sargunv.pokekotlin.models

import dev.sargunv.pokekotlin.models.AbilityDetailPokemonInnerPokemon
import dev.sargunv.pokekotlin.models.GenerationSummary
import dev.sargunv.pokekotlin.models.VersionSummary

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param name 
 * @param generation 
 * @param moveLearnMethods 
 * @param pokedexes 
 * @param regions 
 * @param versions 
 * @param order 
 */
@Serializable

public data class VersionGroupDetail (

    @SerialName(value = "id") @Required val id: kotlin.Int,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "generation") @Required val generation: GenerationSummary,

    @SerialName(value = "move_learn_methods") @Required val moveLearnMethods: kotlin.collections.List<AbilityDetailPokemonInnerPokemon>,

    @SerialName(value = "pokedexes") @Required val pokedexes: kotlin.collections.List<AbilityDetailPokemonInnerPokemon>,

    @SerialName(value = "regions") @Required val regions: kotlin.collections.List<AbilityDetailPokemonInnerPokemon>,

    @SerialName(value = "versions") @Required val versions: kotlin.collections.List<VersionSummary>,

    @SerialName(value = "order") val order: kotlin.Int? = null

) {


}

