[versions]
# Regular libraries: keep as up to date as possible.
kotlinx-serialization = "1.8.1"
ktor = "3.1.3"
snakeyaml = "2.4"

# PokeAPI API spec: examine details in codegen upon update
pokeapi = "2.9.0"


# Regular tools: keep as up to date as possible
gradle-kotlin = "2.1.21"
gradle-dokka = "2.0.0"
gradle-download = "5.6.0"
gradle-jgitver = "0.10.0-rc03"
gradle-mavenPublish = "0.32.0"
gradle-mkdocs = "4.0.1"
gradle-openapiGenerator = "7.12.0"
gradle-spotless = "7.0.4"
tool-prettier = "3.5.3"

[libraries]
# Real dependencies
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

# Used in build tooling only
snakeyaml = { module = "org.yaml:snakeyaml", version.ref = "snakeyaml" }

# Deprecated
okhttp-mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version = "3.14.8" }

[plugins]
dokka = { id = "org.jetbrains.dokka", version.ref = "gradle-dokka" }
download = { id = "de.undercouch.download", version.ref = "gradle-download" }
jgitver = { id = "fr.brouillard.oss.gradle.jgitver", version.ref = "gradle-jgitver" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "gradle-kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "gradle-kotlin" }
mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "gradle-mavenPublish" }
mkdocs = { id = "ru.vyarus.mkdocs-build", version.ref = "gradle-mkdocs" }
openapiGenerator = { id = "org.openapi.generator", version.ref = "gradle-openapiGenerator" }
spotless = { id = "com.diffplug.spotless", version.ref = "gradle-spotless" }
