/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.sargunv.pokekotlin.apis

import dev.sargunv.pokekotlin.models.AbilityDetail
import dev.sargunv.pokekotlin.models.CharacteristicDetail
import dev.sargunv.pokekotlin.models.EggGroupDetail
import dev.sargunv.pokekotlin.models.GenderDetail
import dev.sargunv.pokekotlin.models.GrowthRateDetail
import dev.sargunv.pokekotlin.models.MoveDamageClassDetail
import dev.sargunv.pokekotlin.models.NatureDetail
import dev.sargunv.pokekotlin.models.PaginatedAbilitySummaryList
import dev.sargunv.pokekotlin.models.PaginatedCharacteristicSummaryList
import dev.sargunv.pokekotlin.models.PaginatedEggGroupSummaryList
import dev.sargunv.pokekotlin.models.PaginatedGenderSummaryList
import dev.sargunv.pokekotlin.models.PaginatedGrowthRateSummaryList
import dev.sargunv.pokekotlin.models.PaginatedMoveDamageClassSummaryList
import dev.sargunv.pokekotlin.models.PaginatedNatureSummaryList
import dev.sargunv.pokekotlin.models.PaginatedPokeathlonStatSummaryList
import dev.sargunv.pokekotlin.models.PaginatedPokemonColorSummaryList
import dev.sargunv.pokekotlin.models.PaginatedPokemonFormSummaryList
import dev.sargunv.pokekotlin.models.PaginatedPokemonHabitatSummaryList
import dev.sargunv.pokekotlin.models.PaginatedPokemonShapeSummaryList
import dev.sargunv.pokekotlin.models.PaginatedPokemonSpeciesSummaryList
import dev.sargunv.pokekotlin.models.PaginatedPokemonSummaryList
import dev.sargunv.pokekotlin.models.PaginatedStatSummaryList
import dev.sargunv.pokekotlin.models.PaginatedTypeSummaryList
import dev.sargunv.pokekotlin.models.PokeathlonStatDetail
import dev.sargunv.pokekotlin.models.PokemonColorDetail
import dev.sargunv.pokekotlin.models.PokemonDetail
import dev.sargunv.pokekotlin.models.PokemonFormDetail
import dev.sargunv.pokekotlin.models.PokemonHabitatDetail
import dev.sargunv.pokekotlin.models.PokemonShapeDetail
import dev.sargunv.pokekotlin.models.PokemonSpeciesDetail
import dev.sargunv.pokekotlin.models.StatDetail
import dev.sargunv.pokekotlin.models.TypeDetail

import dev.sargunv.pokekotlin.infrastructure.*
import io.ktor.client.HttpClient
import io.ktor.client.HttpClientConfig
import io.ktor.client.request.forms.formData
import io.ktor.client.engine.HttpClientEngine
import kotlinx.serialization.json.Json
import io.ktor.http.ParametersBuilder
import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

public open class PokemonApi : ApiClient {

    public constructor(
        baseUrl: String = ApiClient.BASE_URL,
        httpClientEngine: HttpClientEngine? = null,
        httpClientConfig: ((HttpClientConfig<*>) -> Unit)? = null,
        jsonSerializer: Json = ApiClient.JSON_DEFAULT
    ) : super(baseUrl = baseUrl, httpClientEngine = httpClientEngine, httpClientConfig = httpClientConfig, jsonBlock = jsonSerializer)

    public constructor(
        baseUrl: String,
        httpClient: HttpClient
    ): super(baseUrl = baseUrl, httpClient = httpClient)

    /**
     * 
     * Abilities provide passive effects for Pokémon in battle or in the overworld. Pokémon have multiple possible abilities but can have only one ability at a time. Check out [Bulbapedia](http://bulbapedia.bulbagarden.net/wiki/Ability) for greater detail.
     * @param limit Number of results to return per page. (optional)
     * @param offset The initial index from which to return the results. (optional)
     * @param q &gt; Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2) Case-insensitive query applied on the &#x60;name&#x60; property.  (optional)
     * @return PaginatedAbilitySummaryList
     */
    @Suppress("UNCHECKED_CAST")
    public open suspend fun abilityList(limit: kotlin.Int? = null, offset: kotlin.Int? = null, q: kotlin.String? = null): HttpResponse<PaginatedAbilitySummaryList> {

        val localVariableAuthNames = listOf<String>("basicAuth", "cookieAuth")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        limit?.apply { localVariableQuery["limit"] = listOf("$limit") }
        offset?.apply { localVariableQuery["offset"] = listOf("$offset") }
        q?.apply { localVariableQuery["q"] = listOf("$q") }
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v2/ability/",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * 
     * Abilities provide passive effects for Pokémon in battle or in the overworld. Pokémon have multiple possible abilities but can have only one ability at a time. Check out [Bulbapedia](http://bulbapedia.bulbagarden.net/wiki/Ability) for greater detail.
     * @param id This parameter can be a string or an integer.
     * @return AbilityDetail
     */
    @Suppress("UNCHECKED_CAST")
    public open suspend fun abilityRetrieve(id: kotlin.String): HttpResponse<AbilityDetail> {

        val localVariableAuthNames = listOf<String>("basicAuth", "cookieAuth")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v2/ability/{id}/".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * List charecterictics
     * Characteristics indicate which stat contains a Pokémon&#39;s highest IV. A Pokémon&#39;s Characteristic is determined by the remainder of its highest IV divided by 5 (gene_modulo). Check out [Bulbapedia](http://bulbapedia.bulbagarden.net/wiki/Characteristic) for greater detail.
     * @param limit Number of results to return per page. (optional)
     * @param offset The initial index from which to return the results. (optional)
     * @param q &gt; Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2) Case-insensitive query applied on the &#x60;name&#x60; property.  (optional)
     * @return PaginatedCharacteristicSummaryList
     */
    @Suppress("UNCHECKED_CAST")
    public open suspend fun characteristicList(limit: kotlin.Int? = null, offset: kotlin.Int? = null, q: kotlin.String? = null): HttpResponse<PaginatedCharacteristicSummaryList> {

        val localVariableAuthNames = listOf<String>("basicAuth", "cookieAuth")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        limit?.apply { localVariableQuery["limit"] = listOf("$limit") }
        offset?.apply { localVariableQuery["offset"] = listOf("$offset") }
        q?.apply { localVariableQuery["q"] = listOf("$q") }
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v2/characteristic/",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * Get characteristic
     * Characteristics indicate which stat contains a Pokémon&#39;s highest IV. A Pokémon&#39;s Characteristic is determined by the remainder of its highest IV divided by 5 (gene_modulo). Check out [Bulbapedia](http://bulbapedia.bulbagarden.net/wiki/Characteristic) for greater detail.
     * @param id This parameter can be a string or an integer.
     * @return CharacteristicDetail
     */
    @Suppress("UNCHECKED_CAST")
    public open suspend fun characteristicRetrieve(id: kotlin.String): HttpResponse<CharacteristicDetail> {

        val localVariableAuthNames = listOf<String>("basicAuth", "cookieAuth")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v2/characteristic/{id}/".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * List egg groups
     * Egg Groups are categories which determine which Pokémon are able to interbreed. Pokémon may belong to either one or two Egg Groups. Check out [Bulbapedia](http://bulbapedia.bulbagarden.net/wiki/Egg_Group) for greater detail.
     * @param limit Number of results to return per page. (optional)
     * @param offset The initial index from which to return the results. (optional)
     * @param q &gt; Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2) Case-insensitive query applied on the &#x60;name&#x60; property.  (optional)
     * @return PaginatedEggGroupSummaryList
     */
    @Suppress("UNCHECKED_CAST")
    public open suspend fun eggGroupList(limit: kotlin.Int? = null, offset: kotlin.Int? = null, q: kotlin.String? = null): HttpResponse<PaginatedEggGroupSummaryList> {

        val localVariableAuthNames = listOf<String>("basicAuth", "cookieAuth")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        limit?.apply { localVariableQuery["limit"] = listOf("$limit") }
        offset?.apply { localVariableQuery["offset"] = listOf("$offset") }
        q?.apply { localVariableQuery["q"] = listOf("$q") }
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v2/egg-group/",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * Get egg group
     * Egg Groups are categories which determine which Pokémon are able to interbreed. Pokémon may belong to either one or two Egg Groups. Check out [Bulbapedia](http://bulbapedia.bulbagarden.net/wiki/Egg_Group) for greater detail.
     * @param id This parameter can be a string or an integer.
     * @return EggGroupDetail
     */
    @Suppress("UNCHECKED_CAST")
    public open suspend fun eggGroupRetrieve(id: kotlin.String): HttpResponse<EggGroupDetail> {

        val localVariableAuthNames = listOf<String>("basicAuth", "cookieAuth")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v2/egg-group/{id}/".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * List genders
     * Genders were introduced in Generation II for the purposes of breeding Pokémon but can also result in visual differences or even different evolutionary lines. Check out [Bulbapedia](http://bulbapedia.bulbagarden.net/wiki/Gender) for greater detail.
     * @param limit Number of results to return per page. (optional)
     * @param offset The initial index from which to return the results. (optional)
     * @param q &gt; Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2) Case-insensitive query applied on the &#x60;name&#x60; property.  (optional)
     * @return PaginatedGenderSummaryList
     */
    @Suppress("UNCHECKED_CAST")
    public open suspend fun genderList(limit: kotlin.Int? = null, offset: kotlin.Int? = null, q: kotlin.String? = null): HttpResponse<PaginatedGenderSummaryList> {

        val localVariableAuthNames = listOf<String>("basicAuth", "cookieAuth")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        limit?.apply { localVariableQuery["limit"] = listOf("$limit") }
        offset?.apply { localVariableQuery["offset"] = listOf("$offset") }
        q?.apply { localVariableQuery["q"] = listOf("$q") }
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v2/gender/",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * Get gender
     * Genders were introduced in Generation II for the purposes of breeding Pokémon but can also result in visual differences or even different evolutionary lines. Check out [Bulbapedia](http://bulbapedia.bulbagarden.net/wiki/Gender) for greater detail.
     * @param id This parameter can be a string or an integer.
     * @return GenderDetail
     */
    @Suppress("UNCHECKED_CAST")
    public open suspend fun genderRetrieve(id: kotlin.String): HttpResponse<GenderDetail> {

        val localVariableAuthNames = listOf<String>("basicAuth", "cookieAuth")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v2/gender/{id}/".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * List growth rates
     * Growth rates are the speed with which Pokémon gain levels through experience. Check out [Bulbapedia](http://bulbapedia.bulbagarden.net/wiki/Experience) for greater detail.
     * @param limit Number of results to return per page. (optional)
     * @param offset The initial index from which to return the results. (optional)
     * @param q &gt; Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2) Case-insensitive query applied on the &#x60;name&#x60; property.  (optional)
     * @return PaginatedGrowthRateSummaryList
     */
    @Suppress("UNCHECKED_CAST")
    public open suspend fun growthRateList(limit: kotlin.Int? = null, offset: kotlin.Int? = null, q: kotlin.String? = null): HttpResponse<PaginatedGrowthRateSummaryList> {

        val localVariableAuthNames = listOf<String>("basicAuth", "cookieAuth")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        limit?.apply { localVariableQuery["limit"] = listOf("$limit") }
        offset?.apply { localVariableQuery["offset"] = listOf("$offset") }
        q?.apply { localVariableQuery["q"] = listOf("$q") }
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v2/growth-rate/",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * Get growth rate
     * Growth rates are the speed with which Pokémon gain levels through experience. Check out [Bulbapedia](http://bulbapedia.bulbagarden.net/wiki/Experience) for greater detail.
     * @param id This parameter can be a string or an integer.
     * @return GrowthRateDetail
     */
    @Suppress("UNCHECKED_CAST")
    public open suspend fun growthRateRetrieve(id: kotlin.String): HttpResponse<GrowthRateDetail> {

        val localVariableAuthNames = listOf<String>("basicAuth", "cookieAuth")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v2/growth-rate/{id}/".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * List move damage classes
     * Damage classes moves can have, e.g. physical, special, or non-damaging.
     * @param limit Number of results to return per page. (optional)
     * @param offset The initial index from which to return the results. (optional)
     * @param q &gt; Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2) Case-insensitive query applied on the &#x60;name&#x60; property.  (optional)
     * @return PaginatedMoveDamageClassSummaryList
     */
    @Suppress("UNCHECKED_CAST")
    public open suspend fun moveDamageClassList(limit: kotlin.Int? = null, offset: kotlin.Int? = null, q: kotlin.String? = null): HttpResponse<PaginatedMoveDamageClassSummaryList> {

        val localVariableAuthNames = listOf<String>("basicAuth", "cookieAuth")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        limit?.apply { localVariableQuery["limit"] = listOf("$limit") }
        offset?.apply { localVariableQuery["offset"] = listOf("$offset") }
        q?.apply { localVariableQuery["q"] = listOf("$q") }
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v2/move-damage-class/",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * Get move damage class
     * Damage classes moves can have, e.g. physical, special, or non-damaging.
     * @param id This parameter can be a string or an integer.
     * @return MoveDamageClassDetail
     */
    @Suppress("UNCHECKED_CAST")
    public open suspend fun moveDamageClassRetrieve(id: kotlin.String): HttpResponse<MoveDamageClassDetail> {

        val localVariableAuthNames = listOf<String>("basicAuth", "cookieAuth")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v2/move-damage-class/{id}/".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * List natures
     * Natures influence how a Pokémon&#39;s stats grow. See [Bulbapedia](http://bulbapedia.bulbagarden.net/wiki/Nature) for greater detail.
     * @param limit Number of results to return per page. (optional)
     * @param offset The initial index from which to return the results. (optional)
     * @param q &gt; Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2) Case-insensitive query applied on the &#x60;name&#x60; property.  (optional)
     * @return PaginatedNatureSummaryList
     */
    @Suppress("UNCHECKED_CAST")
    public open suspend fun natureList(limit: kotlin.Int? = null, offset: kotlin.Int? = null, q: kotlin.String? = null): HttpResponse<PaginatedNatureSummaryList> {

        val localVariableAuthNames = listOf<String>("basicAuth", "cookieAuth")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        limit?.apply { localVariableQuery["limit"] = listOf("$limit") }
        offset?.apply { localVariableQuery["offset"] = listOf("$offset") }
        q?.apply { localVariableQuery["q"] = listOf("$q") }
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v2/nature/",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * Get nature
     * Natures influence how a Pokémon&#39;s stats grow. See [Bulbapedia](http://bulbapedia.bulbagarden.net/wiki/Nature) for greater detail.
     * @param id This parameter can be a string or an integer.
     * @return NatureDetail
     */
    @Suppress("UNCHECKED_CAST")
    public open suspend fun natureRetrieve(id: kotlin.String): HttpResponse<NatureDetail> {

        val localVariableAuthNames = listOf<String>("basicAuth", "cookieAuth")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v2/nature/{id}/".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * List pokeathlon stats
     * Pokeathlon Stats are different attributes of a Pokémon&#39;s performance in Pokéathlons. In Pokéathlons, competitions happen on different courses; one for each of the different Pokéathlon stats. See [Bulbapedia](http://bulbapedia.bulbagarden.net/wiki/Pok%C3%A9athlon) for greater detail.
     * @param limit Number of results to return per page. (optional)
     * @param offset The initial index from which to return the results. (optional)
     * @param q &gt; Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2) Case-insensitive query applied on the &#x60;name&#x60; property.  (optional)
     * @return PaginatedPokeathlonStatSummaryList
     */
    @Suppress("UNCHECKED_CAST")
    public open suspend fun pokeathlonStatList(limit: kotlin.Int? = null, offset: kotlin.Int? = null, q: kotlin.String? = null): HttpResponse<PaginatedPokeathlonStatSummaryList> {

        val localVariableAuthNames = listOf<String>("basicAuth", "cookieAuth")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        limit?.apply { localVariableQuery["limit"] = listOf("$limit") }
        offset?.apply { localVariableQuery["offset"] = listOf("$offset") }
        q?.apply { localVariableQuery["q"] = listOf("$q") }
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v2/pokeathlon-stat/",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * Get pokeathlon stat
     * Pokeathlon Stats are different attributes of a Pokémon&#39;s performance in Pokéathlons. In Pokéathlons, competitions happen on different courses; one for each of the different Pokéathlon stats. See [Bulbapedia](http://bulbapedia.bulbagarden.net/wiki/Pok%C3%A9athlon) for greater detail.
     * @param id This parameter can be a string or an integer.
     * @return PokeathlonStatDetail
     */
    @Suppress("UNCHECKED_CAST")
    public open suspend fun pokeathlonStatRetrieve(id: kotlin.String): HttpResponse<PokeathlonStatDetail> {

        val localVariableAuthNames = listOf<String>("basicAuth", "cookieAuth")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v2/pokeathlon-stat/{id}/".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * List pokemon colors
     * Colors used for sorting Pokémon in a Pokédex. The color listed in the Pokédex is usually the color most apparent or covering each Pokémon&#39;s body. No orange category exists; Pokémon that are primarily orange are listed as red or brown.
     * @param limit Number of results to return per page. (optional)
     * @param offset The initial index from which to return the results. (optional)
     * @param q &gt; Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2) Case-insensitive query applied on the &#x60;name&#x60; property.  (optional)
     * @return PaginatedPokemonColorSummaryList
     */
    @Suppress("UNCHECKED_CAST")
    public open suspend fun pokemonColorList(limit: kotlin.Int? = null, offset: kotlin.Int? = null, q: kotlin.String? = null): HttpResponse<PaginatedPokemonColorSummaryList> {

        val localVariableAuthNames = listOf<String>("basicAuth", "cookieAuth")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        limit?.apply { localVariableQuery["limit"] = listOf("$limit") }
        offset?.apply { localVariableQuery["offset"] = listOf("$offset") }
        q?.apply { localVariableQuery["q"] = listOf("$q") }
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v2/pokemon-color/",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * Get pokemon color
     * Colors used for sorting Pokémon in a Pokédex. The color listed in the Pokédex is usually the color most apparent or covering each Pokémon&#39;s body. No orange category exists; Pokémon that are primarily orange are listed as red or brown.
     * @param id This parameter can be a string or an integer.
     * @return PokemonColorDetail
     */
    @Suppress("UNCHECKED_CAST")
    public open suspend fun pokemonColorRetrieve(id: kotlin.String): HttpResponse<PokemonColorDetail> {

        val localVariableAuthNames = listOf<String>("basicAuth", "cookieAuth")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v2/pokemon-color/{id}/".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * List pokemon forms
     * Some Pokémon may appear in one of multiple, visually different forms. These differences are purely cosmetic. For variations within a Pokémon species, which do differ in more than just visuals, the &#39;Pokémon&#39; entity is used to represent such a variety.
     * @param limit Number of results to return per page. (optional)
     * @param offset The initial index from which to return the results. (optional)
     * @param q &gt; Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2) Case-insensitive query applied on the &#x60;name&#x60; property.  (optional)
     * @return PaginatedPokemonFormSummaryList
     */
    @Suppress("UNCHECKED_CAST")
    public open suspend fun pokemonFormList(limit: kotlin.Int? = null, offset: kotlin.Int? = null, q: kotlin.String? = null): HttpResponse<PaginatedPokemonFormSummaryList> {

        val localVariableAuthNames = listOf<String>("basicAuth", "cookieAuth")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        limit?.apply { localVariableQuery["limit"] = listOf("$limit") }
        offset?.apply { localVariableQuery["offset"] = listOf("$offset") }
        q?.apply { localVariableQuery["q"] = listOf("$q") }
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v2/pokemon-form/",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * Get pokemon form
     * Some Pokémon may appear in one of multiple, visually different forms. These differences are purely cosmetic. For variations within a Pokémon species, which do differ in more than just visuals, the &#39;Pokémon&#39; entity is used to represent such a variety.
     * @param id This parameter can be a string or an integer.
     * @return PokemonFormDetail
     */
    @Suppress("UNCHECKED_CAST")
    public open suspend fun pokemonFormRetrieve(id: kotlin.String): HttpResponse<PokemonFormDetail> {

        val localVariableAuthNames = listOf<String>("basicAuth", "cookieAuth")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v2/pokemon-form/{id}/".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * List pokemom habitas
     * Habitats are generally different terrain Pokémon can be found in but can also be areas designated for rare or legendary Pokémon.
     * @param limit Number of results to return per page. (optional)
     * @param offset The initial index from which to return the results. (optional)
     * @param q &gt; Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2) Case-insensitive query applied on the &#x60;name&#x60; property.  (optional)
     * @return PaginatedPokemonHabitatSummaryList
     */
    @Suppress("UNCHECKED_CAST")
    public open suspend fun pokemonHabitatList(limit: kotlin.Int? = null, offset: kotlin.Int? = null, q: kotlin.String? = null): HttpResponse<PaginatedPokemonHabitatSummaryList> {

        val localVariableAuthNames = listOf<String>("basicAuth", "cookieAuth")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        limit?.apply { localVariableQuery["limit"] = listOf("$limit") }
        offset?.apply { localVariableQuery["offset"] = listOf("$offset") }
        q?.apply { localVariableQuery["q"] = listOf("$q") }
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v2/pokemon-habitat/",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * Get pokemom habita
     * Habitats are generally different terrain Pokémon can be found in but can also be areas designated for rare or legendary Pokémon.
     * @param id This parameter can be a string or an integer.
     * @return PokemonHabitatDetail
     */
    @Suppress("UNCHECKED_CAST")
    public open suspend fun pokemonHabitatRetrieve(id: kotlin.String): HttpResponse<PokemonHabitatDetail> {

        val localVariableAuthNames = listOf<String>("basicAuth", "cookieAuth")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v2/pokemon-habitat/{id}/".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * List pokemon
     * Pokémon are the creatures that inhabit the world of the Pokémon games. They can be caught using Pokéballs and trained by battling with other Pokémon. Each Pokémon belongs to a specific species but may take on a variant which makes it differ from other Pokémon of the same species, such as base stats, available abilities and typings. See [Bulbapedia](http://bulbapedia.bulbagarden.net/wiki/Pok%C3%A9mon_(species)) for greater detail.
     * @param limit Number of results to return per page. (optional)
     * @param offset The initial index from which to return the results. (optional)
     * @param q &gt; Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2) Case-insensitive query applied on the &#x60;name&#x60; property.  (optional)
     * @return PaginatedPokemonSummaryList
     */
    @Suppress("UNCHECKED_CAST")
    public open suspend fun pokemonList(limit: kotlin.Int? = null, offset: kotlin.Int? = null, q: kotlin.String? = null): HttpResponse<PaginatedPokemonSummaryList> {

        val localVariableAuthNames = listOf<String>("basicAuth", "cookieAuth")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        limit?.apply { localVariableQuery["limit"] = listOf("$limit") }
        offset?.apply { localVariableQuery["offset"] = listOf("$offset") }
        q?.apply { localVariableQuery["q"] = listOf("$q") }
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v2/pokemon/",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * Get pokemon
     * Pokémon are the creatures that inhabit the world of the Pokémon games. They can be caught using Pokéballs and trained by battling with other Pokémon. Each Pokémon belongs to a specific species but may take on a variant which makes it differ from other Pokémon of the same species, such as base stats, available abilities and typings. See [Bulbapedia](http://bulbapedia.bulbagarden.net/wiki/Pok%C3%A9mon_(species)) for greater detail.
     * @param id This parameter can be a string or an integer.
     * @return PokemonDetail
     */
    @Suppress("UNCHECKED_CAST")
    public open suspend fun pokemonRetrieve(id: kotlin.String): HttpResponse<PokemonDetail> {

        val localVariableAuthNames = listOf<String>("basicAuth", "cookieAuth")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v2/pokemon/{id}/".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * List pokemon shapes
     * Shapes used for sorting Pokémon in a Pokédex.
     * @param limit Number of results to return per page. (optional)
     * @param offset The initial index from which to return the results. (optional)
     * @param q &gt; Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2) Case-insensitive query applied on the &#x60;name&#x60; property.  (optional)
     * @return PaginatedPokemonShapeSummaryList
     */
    @Suppress("UNCHECKED_CAST")
    public open suspend fun pokemonShapeList(limit: kotlin.Int? = null, offset: kotlin.Int? = null, q: kotlin.String? = null): HttpResponse<PaginatedPokemonShapeSummaryList> {

        val localVariableAuthNames = listOf<String>("basicAuth", "cookieAuth")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        limit?.apply { localVariableQuery["limit"] = listOf("$limit") }
        offset?.apply { localVariableQuery["offset"] = listOf("$offset") }
        q?.apply { localVariableQuery["q"] = listOf("$q") }
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v2/pokemon-shape/",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * Get pokemon shape
     * Shapes used for sorting Pokémon in a Pokédex.
     * @param id This parameter can be a string or an integer.
     * @return PokemonShapeDetail
     */
    @Suppress("UNCHECKED_CAST")
    public open suspend fun pokemonShapeRetrieve(id: kotlin.String): HttpResponse<PokemonShapeDetail> {

        val localVariableAuthNames = listOf<String>("basicAuth", "cookieAuth")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v2/pokemon-shape/{id}/".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * List pokemon species
     * A Pokémon Species forms the basis for at least one Pokémon. Attributes of a Pokémon species are shared across all varieties of Pokémon within the species. A good example is Wormadam; Wormadam is the species which can be found in three different varieties, Wormadam-Trash, Wormadam-Sandy and Wormadam-Plant.
     * @param limit Number of results to return per page. (optional)
     * @param offset The initial index from which to return the results. (optional)
     * @param q &gt; Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2) Case-insensitive query applied on the &#x60;name&#x60; property.  (optional)
     * @return PaginatedPokemonSpeciesSummaryList
     */
    @Suppress("UNCHECKED_CAST")
    public open suspend fun pokemonSpeciesList(limit: kotlin.Int? = null, offset: kotlin.Int? = null, q: kotlin.String? = null): HttpResponse<PaginatedPokemonSpeciesSummaryList> {

        val localVariableAuthNames = listOf<String>("basicAuth", "cookieAuth")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        limit?.apply { localVariableQuery["limit"] = listOf("$limit") }
        offset?.apply { localVariableQuery["offset"] = listOf("$offset") }
        q?.apply { localVariableQuery["q"] = listOf("$q") }
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v2/pokemon-species/",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * Get pokemon species
     * A Pokémon Species forms the basis for at least one Pokémon. Attributes of a Pokémon species are shared across all varieties of Pokémon within the species. A good example is Wormadam; Wormadam is the species which can be found in three different varieties, Wormadam-Trash, Wormadam-Sandy and Wormadam-Plant.
     * @param id This parameter can be a string or an integer.
     * @return PokemonSpeciesDetail
     */
    @Suppress("UNCHECKED_CAST")
    public open suspend fun pokemonSpeciesRetrieve(id: kotlin.String): HttpResponse<PokemonSpeciesDetail> {

        val localVariableAuthNames = listOf<String>("basicAuth", "cookieAuth")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v2/pokemon-species/{id}/".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * List stats
     * Stats determine certain aspects of battles. Each Pokémon has a value for each stat which grows as they gain levels and can be altered momentarily by effects in battles.
     * @param limit Number of results to return per page. (optional)
     * @param offset The initial index from which to return the results. (optional)
     * @param q &gt; Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2) Case-insensitive query applied on the &#x60;name&#x60; property.  (optional)
     * @return PaginatedStatSummaryList
     */
    @Suppress("UNCHECKED_CAST")
    public open suspend fun statList(limit: kotlin.Int? = null, offset: kotlin.Int? = null, q: kotlin.String? = null): HttpResponse<PaginatedStatSummaryList> {

        val localVariableAuthNames = listOf<String>("basicAuth", "cookieAuth")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        limit?.apply { localVariableQuery["limit"] = listOf("$limit") }
        offset?.apply { localVariableQuery["offset"] = listOf("$offset") }
        q?.apply { localVariableQuery["q"] = listOf("$q") }
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v2/stat/",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * Get stat
     * Stats determine certain aspects of battles. Each Pokémon has a value for each stat which grows as they gain levels and can be altered momentarily by effects in battles.
     * @param id This parameter can be a string or an integer.
     * @return StatDetail
     */
    @Suppress("UNCHECKED_CAST")
    public open suspend fun statRetrieve(id: kotlin.String): HttpResponse<StatDetail> {

        val localVariableAuthNames = listOf<String>("basicAuth", "cookieAuth")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v2/stat/{id}/".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * List types
     * Types are properties for Pokémon and their moves. Each type has three properties: which types of Pokémon it is super effective against, which types of Pokémon it is not very effective against, and which types of Pokémon it is completely ineffective against.
     * @param limit Number of results to return per page. (optional)
     * @param offset The initial index from which to return the results. (optional)
     * @param q &gt; Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2) Case-insensitive query applied on the &#x60;name&#x60; property.  (optional)
     * @return PaginatedTypeSummaryList
     */
    @Suppress("UNCHECKED_CAST")
    public open suspend fun typeList(limit: kotlin.Int? = null, offset: kotlin.Int? = null, q: kotlin.String? = null): HttpResponse<PaginatedTypeSummaryList> {

        val localVariableAuthNames = listOf<String>("basicAuth", "cookieAuth")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        limit?.apply { localVariableQuery["limit"] = listOf("$limit") }
        offset?.apply { localVariableQuery["offset"] = listOf("$offset") }
        q?.apply { localVariableQuery["q"] = listOf("$q") }
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v2/type/",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * Get types
     * Types are properties for Pokémon and their moves. Each type has three properties: which types of Pokémon it is super effective against, which types of Pokémon it is not very effective against, and which types of Pokémon it is completely ineffective against.
     * @param id This parameter can be a string or an integer.
     * @return TypeDetail
     */
    @Suppress("UNCHECKED_CAST")
    public open suspend fun typeRetrieve(id: kotlin.String): HttpResponse<TypeDetail> {

        val localVariableAuthNames = listOf<String>("basicAuth", "cookieAuth")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v2/type/{id}/".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


}
