name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: jvm
            os: ubuntu
          - target: jsBrowser
            os: ubuntu
          - target: jsNode
            os: ubuntu
          - target: wasmJsBrowser
            os: ubuntu
          - target: wasmJsNode
            os: ubuntu
          - target: wasmJsD8
            os: ubuntu
          - target: linuxX64
            os: ubuntu
          - target: macosArm64
            os: macos
          - target: mingwX64
            os: windows
          - target: iosSimulatorArm64
            os: macos
          - target: tvosSimulatorArm64
            os: macos
          - target: watchosSimulatorArm64
            os: macos
    runs-on: "${{ matrix.os }}-latest"
    name: "test (${{ matrix.target }})"
    steps:
      - uses: "actions/checkout@v4"
        with:
          fetch-depth: 0
      - uses: "./.github/actions/setup"
      - run: "npx -y http-server src/commonTest/resources/data -e json -p 8080 --cors &"
      - run: "./gradlew ${{ matrix.target }}Test"

  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v4"
        with:
          fetch-depth: 0
      - uses: "./.github/actions/setup"
      - run: "./gradlew generateDocs"
      - uses: "actions/upload-pages-artifact@v3"
        with:
          path: "build/docs"

  check-format:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      issues: write
      pull-requests: write
    steps:
      - uses: "actions/checkout@v4"
        with:
          fetch-depth: 0
      - uses: "./.github/actions/setup"
      - run: "./gradlew spotlessApply"
      - if: "${{ github.event_name == 'pull_request' }}"
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: spotless
          cleanup: false
      - run: "git diff --exit-code"

  all-good:
    needs:
      - "test"
      - "check-format"
      - "build-docs"
    runs-on: "ubuntu-latest"
    steps:
      - run: "echo 'All checks passed!'"
