---
name: "Release"

on:
  push:
    tags: ["v*.*.*"]

jobs:
  publish-maven:
    runs-on: macos-latest
    environment:
      name: "maven-central"
      url: "https://central.sonatype.com/namespace/co.pokeapi.pokekotlin"
    steps:
      - uses: "actions/checkout@v4"
        with:
          fetch-depth: 0
      - run: "git fetch --tags --force" # https://github.com/actions/checkout/issues/290
      - uses: "./.github/actions/setup"
      - run: "./gradlew publishAndReleaseToMavenCentral --no-configuration-cache"
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: "${{ secrets.MAVEN_CENTRAL_USERNAME }}"
          ORG_GRADLE_PROJECT_mavenCentralPassword: "${{ secrets.MAVEN_CENTRAL_PASSWORD }}"
          ORG_GRADLE_PROJECT_signingInMemoryKey: "${{ secrets.GPG_PRIVATE_KEY }}"
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: "${{ secrets.GPG_PASSPHRASE }}"

  publish-pages:
    needs:
      - "publish-maven"
    runs-on: macos-latest
    permissions:
      pages: "write"
      id-token: "write"
    environment:
      name: "github-pages"
      url: "${{ steps.deploy-pages.outputs.page_url }}"
    steps:
      - uses: "actions/checkout@v4"
        with:
          fetch-depth: 0
      - run: "git fetch --tags --force" # https://github.com/actions/checkout/issues/290
      - uses: "./.github/actions/setup"
      - run: "./gradlew generateDocs"
      - uses: "actions/upload-pages-artifact@v3"
        with:
          path: "build/docs"
      - uses: "actions/deploy-pages@v4"
        id: "deploy-pages"
